name: daimon-gripper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - ffmpeg
  - pip:
      - -r requirement.txt
      - -e dm_gripper_py
      - -e dm_gripper_tac_py
variables:
  PYTHONNOUSERSITE: "1"
