# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

try:
    from . import camera_proxy_pb2 as camera__proxy__pb2
except ImportError:
    import camera_proxy_pb2 as camera__proxy__pb2


class CameraProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCapabilities = channel.unary_unary(
                '/fish_camera.grpc_test.CameraProxy/ListCapabilities',
                request_serializer=camera__proxy__pb2.CapabilityRequest.SerializeToString,
                response_deserializer=camera__proxy__pb2.CapabilityResponse.FromString)
        self.GetIntrinsics = channel.unary_unary(
                '/fish_camera.grpc_test.CameraProxy/GetIntrinsics',
                request_serializer=camera__proxy__pb2.CalibrationRequest.SerializeToString,
                response_deserializer=camera__proxy__pb2.IntrinsicsResponse.FromString)
        self.GetSN = channel.unary_unary(
                '/fish_camera.grpc_test.CameraProxy/GetSN',
                request_serializer=camera__proxy__pb2.CalibrationRequest.SerializeToString,
                response_deserializer=camera__proxy__pb2.SNResponse.FromString)
        self.OpenStream = channel.unary_stream(
                '/fish_camera.grpc_test.CameraProxy/OpenStream',
                request_serializer=camera__proxy__pb2.StreamRequest.SerializeToString,
                response_deserializer=camera__proxy__pb2.StreamEvent.FromString)
        self.StopStream = channel.unary_unary(
                '/fish_camera.grpc_test.CameraProxy/StopStream',
                request_serializer=camera__proxy__pb2.StopStreamRequest.SerializeToString,
                response_deserializer=camera__proxy__pb2.StopStreamResponse.FromString)


class CameraProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntrinsics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapabilities,
                    request_deserializer=camera__proxy__pb2.CapabilityRequest.FromString,
                    response_serializer=camera__proxy__pb2.CapabilityResponse.SerializeToString,
            ),
            'GetIntrinsics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntrinsics,
                    request_deserializer=camera__proxy__pb2.CalibrationRequest.FromString,
                    response_serializer=camera__proxy__pb2.IntrinsicsResponse.SerializeToString,
            ),
            'GetSN': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSN,
                    request_deserializer=camera__proxy__pb2.CalibrationRequest.FromString,
                    response_serializer=camera__proxy__pb2.SNResponse.SerializeToString,
            ),
            'OpenStream': grpc.unary_stream_rpc_method_handler(
                    servicer.OpenStream,
                    request_deserializer=camera__proxy__pb2.StreamRequest.FromString,
                    response_serializer=camera__proxy__pb2.StreamEvent.SerializeToString,
            ),
            'StopStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStream,
                    request_deserializer=camera__proxy__pb2.StopStreamRequest.FromString,
                    response_serializer=camera__proxy__pb2.StopStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fish_camera.grpc_test.CameraProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CameraProxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fish_camera.grpc_test.CameraProxy/ListCapabilities',
            camera__proxy__pb2.CapabilityRequest.SerializeToString,
            camera__proxy__pb2.CapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def GetIntrinsics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fish_camera.grpc_test.CameraProxy/GetIntrinsics',
            camera__proxy__pb2.CalibrationRequest.SerializeToString,
            camera__proxy__pb2.IntrinsicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def GetSN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fish_camera.grpc_test.CameraProxy/GetSN',
            camera__proxy__pb2.CalibrationRequest.SerializeToString,
            camera__proxy__pb2.SNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def OpenStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fish_camera.grpc_test.CameraProxy/OpenStream',
            camera__proxy__pb2.StreamRequest.SerializeToString,
            camera__proxy__pb2.StreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def StopStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fish_camera.grpc_test.CameraProxy/StopStream',
            camera__proxy__pb2.StopStreamRequest.SerializeToString,
            camera__proxy__pb2.StopStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
