# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: can_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
try:
    from google.protobuf import runtime_version as _runtime_version
except ImportError:
    _runtime_version = None

if _runtime_version is not None:
    _runtime_version.ValidateProtobufRuntimeVersion(
        _runtime_version.Domain.PUBLIC,
        6,
        31,
        1,
        '',
        'can_service.proto'
    )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61n_service.proto\x12\x0b\x63\x61n_service\"b\n\nCanMessage\x12\x0e\n\x06\x63\x61n_id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x13\n\x0bis_extended\x18\x03 \x01(\x08\x12\x0e\n\x06is_rtr\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\"]\n\x0e\x43\x61nInitRequest\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0f\n\x07\x62itrate\x18\x02 \x01(\r\x12\x10\n\x08loopback\x18\x03 \x01(\x08\x12\x15\n\rrecv_own_msgs\x18\x04 \x01(\x08\"3\n\x0f\x43\x61nInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x0b\x43\x61nResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"f\n\x0e\x43\x61nRecvRequest\x12\x17\n\ntimeout_ms\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x1a\n\rcan_id_filter\x18\x02 \x01(\rH\x01\x88\x01\x01\x42\r\n\x0b_timeout_msB\x10\n\x0e_can_id_filter2\xd3\x01\n\nCanService\x12\x44\n\x07InitCan\x12\x1b.can_service.CanInitRequest\x1a\x1c.can_service.CanInitResponse\x12<\n\x07SendCan\x12\x17.can_service.CanMessage\x1a\x18.can_service.CanResponse\x12\x41\n\x07RecvCan\x12\x1b.can_service.CanRecvRequest\x1a\x17.can_service.CanMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'can_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANMESSAGE']._serialized_start=34
  _globals['_CANMESSAGE']._serialized_end=132
  _globals['_CANINITREQUEST']._serialized_start=134
  _globals['_CANINITREQUEST']._serialized_end=227
  _globals['_CANINITRESPONSE']._serialized_start=229
  _globals['_CANINITRESPONSE']._serialized_end=280
  _globals['_CANRESPONSE']._serialized_start=282
  _globals['_CANRESPONSE']._serialized_end=329
  _globals['_CANRECVREQUEST']._serialized_start=331
  _globals['_CANRECVREQUEST']._serialized_end=433
  _globals['_CANSERVICE']._serialized_start=436
  _globals['_CANSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
