# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
from . import can_service_pb2 as can__service__pb2


GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in can_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitCan = channel.unary_unary(
                '/can_service.CanService/InitCan',
                request_serializer=can__service__pb2.CanInitRequest.SerializeToString,
                response_deserializer=can__service__pb2.CanInitResponse.FromString,
                _registered_method=True)
        self.SendCan = channel.unary_unary(
                '/can_service.CanService/SendCan',
                request_serializer=can__service__pb2.CanMessage.SerializeToString,
                response_deserializer=can__service__pb2.CanResponse.FromString,
                _registered_method=True)
        self.RecvCan = channel.unary_stream(
                '/can_service.CanService/RecvCan',
                request_serializer=can__service__pb2.CanRecvRequest.SerializeToString,
                response_deserializer=can__service__pb2.CanMessage.FromString,
                _registered_method=True)


class CanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitCan(self, request, context):
        """Initialize CAN interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCan(self, request, context):
        """Send CAN message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecvCan(self, request, context):
        """Receive CAN messages (streaming response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitCan': grpc.unary_unary_rpc_method_handler(
                    servicer.InitCan,
                    request_deserializer=can__service__pb2.CanInitRequest.FromString,
                    response_serializer=can__service__pb2.CanInitResponse.SerializeToString,
            ),
            'SendCan': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCan,
                    request_deserializer=can__service__pb2.CanMessage.FromString,
                    response_serializer=can__service__pb2.CanResponse.SerializeToString,
            ),
            'RecvCan': grpc.unary_stream_rpc_method_handler(
                    servicer.RecvCan,
                    request_deserializer=can__service__pb2.CanRecvRequest.FromString,
                    response_serializer=can__service__pb2.CanMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'can_service.CanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('can_service.CanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitCan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/can_service.CanService/InitCan',
            can__service__pb2.CanInitRequest.SerializeToString,
            can__service__pb2.CanInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/can_service.CanService/SendCan',
            can__service__pb2.CanMessage.SerializeToString,
            can__service__pb2.CanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecvCan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/can_service.CanService/RecvCan',
            can__service__pb2.CanRecvRequest.SerializeToString,
            can__service__pb2.CanMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
